import { sitePath } from '@/lib/site-path';
import { ArrowUpRight, ArrowRight } from 'lucide-react';
import { SiteHeader } from '@/components/site-header';
import { SiteFooter } from '@/components/site-footer';
import { PrintHero, CollageMotion, AtelierBand } from '@/components/print-studio';
import { InkSplitViewer } from '@/components/inksplit-viewer';
import { ProjectArt } from '@/components/project-art';
import { ProjectPanelProvider, ProjectLink } from '@/components/project-panel';
import { projects, featuredProjects, archiveProjects, articles } from '@/lib/portfolio';
export default function Home() {
  return <ProjectPanelProvider projects={projects}><div id="top" className="comic-home"><SiteHeader/>
    <main id="main"><CollageMotion/><PrintHero/><AtelierBand/>
      <section id="work" className="work-section wrap" aria-labelledby="work-title">
        <div className="print-section-heading" data-reveal><div><span className="chapter-label">01 / THE WORK</span><h2 id="work-title">Different worlds.<br/><em>Same curious streak.</em></h2></div><p>From Olympic competition apparel to independent software. Ideas made real, in whatever form they need.</p></div>
        <div className="project-grid">{featuredProjects.map((project, i) => <article className={`project-card project-position-${i + 1}`} key={project.id} data-reveal>
          <div className="panel-masthead"><span>FIELD NOTES / {String(i + 1).padStart(2, '0')}</span><span>{project.tags[0]}</span></div>
          <ProjectLink className={`project-visual ${project.id}-visual`} projectId={project.id} aria-label={`View ${project.originalTitle}`}><ProjectArt project={project}/><span className="image-badge">{project.label.split(' · ')[0]}</span><span className="project-arrow"><ArrowUpRight size={23}/></span></ProjectLink>
          <div className="project-caption"><div className="project-info"><h3><ProjectLink projectId={project.id}>{project.title}</ProjectLink></h3><span>{project.tags.slice(0, 2).join(' · ')}</span></div><p>{project.summary}</p></div>
        </article>)}</div>
      </section>
      <section className="archive-section wrap" aria-labelledby="archive-title"><div className="section-heading"><h2 id="archive-title">And the plot thickens.</h2><span>MORE CLIENT WORK & INDEPENDENT PROJECTS</span></div><div className="archive-list">{archiveProjects.map((project, i) => <ProjectLink projectId={project.id} className="archive-row" key={project.id}><span className="archive-number">{String(i + featuredProjects.length + 1).padStart(2, '0')}</span><div className="archive-name"><h3>{project.originalTitle}</h3><p>{project.summary}</p></div><span className="archive-discipline">{project.tags.join(' / ')}</span><ArrowUpRight size={23}/></ProjectLink>)}</div></section>
      <section className="print-lab" aria-labelledby="featured-article-title"><div className="wrap"><div className="print-section-heading" data-reveal><div><span className="chapter-label">02 / BETWEEN THE LAYERS</span><h2 id="featured-article-title">There’s always<br/><em>more underneath.</em></h2></div><p>A finished image hides its decisions. I’m exploring how AI can turn what we see into something we can edit.</p></div><div className="lab-layout"><div className="lab-note"><span className="print-caption">AN EXPERIMENT IN LOOKING CLOSER</span><h3>Pull it apart.<br/>See how it’s made.</h3><p>Play these InkSplit reconstructions layer by layer, or isolate a piece to inspect it. The interesting part is how everything fits together.</p><a className="print-button" href={sitePath('/writing/turning-visual-knowledge-into-llm-knowledge')}>Read the story <ArrowUpRight size={18}/></a><span className="lab-footnote">INTERPRETED RECONSTRUCTIONS,<br/>NOT RECOVERED ORIGINAL FILES.</span></div><InkSplitViewer/></div></div></section>
      <section id="about" className="about-section wrap" aria-labelledby="about-title"><div className="about-copy" data-reveal><span className="chapter-label">03 / THE PERSON BEHIND THE PANELS</span><h2 id="about-title">A designer.<br/>A developer.<br/><em>A dad.</em></h2><p>I’m Shelby Klein, based in Atlanta, Georgia. I take projects from the first “what if” through the very last detail.</p><p>My work spans national campaigns, Olympic competition apparel, live broadcast systems, and independent hardware and software.</p><p>I’m drawn to creative tools, human–AI interaction, and the places where physical and digital experiences meet.</p><div className="about-links"><a href={sitePath('/Shelby-Klein-Resume.pdf')} target="_blank" rel="noreferrer">The longer story: my resumé <ArrowUpRight size={18}/></a><a href="https://www.linkedin.com/in/shelbyklein/" target="_blank" rel="noreferrer">LinkedIn <ArrowUpRight size={18}/></a></div></div><figure className="portrait" data-reveal><div className="portrait-photo"><img src={sitePath('/images/shelby.webp')} alt="Shelby Klein" width="800" height="1122" loading="lazy"/></div><figcaption><strong>HI, I’M SHELBY.</strong><span>USUALLY MAKING SOMETHING.</span></figcaption></figure></section>
      <section className="practice-section wrap" aria-label="Areas of practice">{[
        ['01', 'Identity & communication', 'Brand systems, campaigns, editorial design, and apparel.'],
        ['02', 'Products & platforms', 'Websites, desktop applications, and physical products.'],
        ['03', 'Motion & experiences', 'Video, live broadcasts, and interactive installations.'],
        ['04', 'Tools & experiments', 'AI workspaces, creative software, and interactive systems.'],
      ].map(([n, title, body]) => <div key={n}><span className="eyebrow">{n}</span><h3>{title}</h3><p>{body}</p></div>)}</section>
      <section className="writing-section wrap" aria-labelledby="writing-title"><div className="print-section-heading" data-reveal><div><span className="chapter-label">04 / FROM THE NOTEBOOK</span><h2 id="writing-title">Thinking out loud.</h2></div><a className="text-link" href={sitePath('/writing')}>All writing <ArrowUpRight size={18}/></a></div><div className="writing-grid">{articles.filter(article => !article.archived).slice(0, 3).map((article, i) => <a className="writing-card" href={sitePath(`/writing/${article.slug}`)} key={article.slug} data-reveal><div className="writing-card-top"><span>NOTE / {String(i + 1).padStart(2, '0')}</span><time dateTime={article.date}>{new Date(article.date + 'T12:00:00Z').toLocaleDateString('en-US', { month: 'short', year: 'numeric', timeZone: 'UTC' })}</time></div><h3>{article.title}</h3><span>Read the story <ArrowRight size={18}/></span></a>)}</div></section>
    </main><SiteFooter/>
  </div></ProjectPanelProvider>;
}
